name: basejmpr
version: 0.0.1 
summary: Package runtime for basejmpr
description: >
   This package provides basejmpr, a tool that makes it easy to create one or
   more kvm instance with a specific configuration and optionally backed by
   an Ubuntu cloud image. It also provides the ability to visualise and manage
   your backing images.
confinement: classic
grade: stable

apps:
  basejmpr:
    command: bin/basejmpr
    plugs:
        - home
        - network
        - libvirt

parts:
  basejmpr:
    source: .
    plugin: python
    python-version: python2
    stage-packages:
      - virt-manager
      - python-jinja2
      - cloud-image-utils
  wrappers:
    plugin: dump
    source: snap/
